# permissions for end users to view databacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databack-viewer-role
rules:
- apiGroups:
  - operator.dct.com
  resources:
  - databacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.dct.com
  resources:
  - databacks/status
  verbs:
  - get
